login:
    path: /login
    defaults: { _controller: ezpublish.security.controller:loginAction }

login_check:
    path: /login_check

logout:
    path: /logout

ezplatform_kernel_internal:
    resource: '@EzPublishCoreBundle/Resources/config/routing/internal.yml'

app.submitted:
    path: /contact/submitted
    defaults:
        _controller: App\Controller\ContactFormController::submittedAction
        template: "@ezdesign/full/contact_form_submitted.html.twig"
    methods: [GET]
