services:
    app.installer.ee-demo_installer:
        parent: ezplatform.installer.db_based_installer
        class: AppBundle\Installer\PlatformEEDemoInstaller
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
        tags:
            - { name: ezplatform.installer, type: ezplatform-ee-demo }

    app.installer.demo-test-layouts_installer:
        parent: ezplatform.installer.db_based_installer
        class: AppBundle\Installer\PlatformEEDemoTestLayoutsInstaller
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
        tags:
            - { name: ezplatform.installer, type: demo-test-layouts }
