ezpublish:
    system:
        admin_group:
            fieldtypes:
                ezrichtext:
                    custom_styles: [highlighted_block, highlighted_word]

ezrichtext:
    custom_styles:
        highlighted_word:
            template: '@ezdesign/fields/ezrichtext/custom_styles/highlighted_word.html.twig'
            inline: true
        highlighted_block:
            template: '@ezdesign/fields/ezrichtext/custom_styles/highlighted_block.html.twig'
            inline: false
